/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Subject = IDL.Variant({
  'media' : IDL.Null,
  'partnership' : IDL.Null,
  'investment' : IDL.Null,
  'general' : IDL.Null,
});
export const Time = IDL.Int;
export const ContactSubmission = IDL.Record({
  'subject' : Subject,
  'name' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'organization' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(ContactSubmission)], ['query']),
  'submitContact' : IDL.Func([IDL.Text, IDL.Text, Subject, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Subject = IDL.Variant({
    'media' : IDL.Null,
    'partnership' : IDL.Null,
    'investment' : IDL.Null,
    'general' : IDL.Null,
  });
  const Time = IDL.Int;
  const ContactSubmission = IDL.Record({
    'subject' : Subject,
    'name' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'organization' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(ContactSubmission)], ['query']),
    'submitContact' : IDL.Func([IDL.Text, IDL.Text, Subject, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };